<?php
if (!defined('ABSPATH')) { exit; }
class CDBM_Admin {
    public function __construct() { add_action('admin_menu', array($this, 'menu')); add_action('admin_post_cdbm_save_box', array($this, 'save')); add_action('admin_post_cdbm_delete_box', array($this, 'delete')); add_action('admin_post_cdbm_save_category', array($this, 'save_category')); add_action('admin_post_cdbm_delete_category', array($this, 'delete_category')); add_action('admin_post_cdbm_save_settings', array($this, 'save_settings')); }
    public function menu() {
        add_menu_page(__('WP Updates Plugin', 'wp-updates-plugin'), __('WP Updates', 'wp-updates-plugin'), 'manage_options', 'wp-updates-plugin', array($this, 'list_page'), 'dashicons-megaphone', 30);
        add_submenu_page('wp-updates-plugin', __('All cards', 'wp-updates-plugin'), __('All cards', 'wp-updates-plugin'), 'manage_options', 'wp-updates-plugin', array($this, 'list_page'));
        add_submenu_page('wp-updates-plugin', __('Add card', 'wp-updates-plugin'), __('Add card', 'wp-updates-plugin'), 'manage_options', 'wp-updates-plugin-add', array($this, 'edit_page'));
    }
    private function url($args = array()) { return add_query_arg($args, admin_url('admin.php?page=wp-updates-plugin')); }
    public function list_page() {
        $tab = isset($_GET['tab']) ? sanitize_key(wp_unslash($_GET['tab'])) : 'cards';
        $tabs = array('cards' => __('All cards', 'wp-updates-plugin'), 'categories' => __('Categories', 'wp-updates-plugin'), 'settings' => __('Settings', 'wp-updates-plugin'), 'how-to-use' => __('How to use', 'wp-updates-plugin')); ?>
        <div class="wrap cdbm-admin-page"><h1 class="wp-heading-inline"><?php esc_html_e('WP Updates', 'wp-updates-plugin'); ?></h1><?php if ($tab === 'cards') : ?><a class="page-title-action" href="<?php echo esc_url(admin_url('admin.php?page=wp-updates-plugin-add')); ?>"><?php esc_html_e('Add card', 'wp-updates-plugin'); ?></a><?php endif; ?><hr class="wp-header-end">
        <nav class="nav-tab-wrapper" aria-label="<?php esc_attr_e('WP Updates sections', 'wp-updates-plugin'); ?>"><?php foreach ($tabs as $key => $label) : ?><a href="<?php echo esc_url($this->url(array('tab' => $key))); ?>" class="nav-tab <?php echo $tab === $key ? 'nav-tab-active' : ''; ?>"><?php echo esc_html($label); ?></a><?php endforeach; ?></nav>
        <?php $this->notices(); if ($tab === 'categories') { $this->categories_tab(); } elseif ($tab === 'settings') { $this->settings_tab(); } elseif ($tab === 'how-to-use') { $this->how_to_use_tab(); } else { $this->cards_tab(); } ?></div><?php
    }
    private function notices() { $messages = array('updated' => __('Card saved.', 'wp-updates-plugin'), 'category-added' => __('Category added.', 'wp-updates-plugin'), 'category-deleted' => __('Category removed.', 'wp-updates-plugin'), 'settings-saved' => __('Settings saved.', 'wp-updates-plugin')); foreach ($messages as $key => $message) { if (isset($_GET[$key])) { echo '<div class="notice notice-success is-dismissible"><p>' . esc_html($message) . '</p></div>'; } } }
    private function cards_tab() { $boxes = CDBM_Database::get_div_boxes(); if (empty($boxes)) { echo '<p>' . esc_html__('No update cards yet.', 'wp-updates-plugin') . '</p>'; return; } ?><div class="cdbm-boxes-list"><?php foreach ($boxes as $box) : ?><article class="cdbm-box-item"><div class="cdbm-box-preview"><div class="cdbm-preview-image"><?php if ($box['image_url']) : ?><img src="<?php echo esc_url($box['image_url']); ?>" alt=""><?php endif; ?></div><div class="cdbm-preview-content"><h3><?php echo esc_html($box['title']); ?></h3><p><?php echo esc_html(wp_trim_words($box['description'], 20)); ?></p><p><strong><?php esc_html_e('Categories:', 'wp-updates-plugin'); ?></strong> <?php echo esc_html(implode(', ', $box['categories'])); ?></p></div></div><div class="cdbm-box-actions"><a class="button button-primary" href="<?php echo esc_url(admin_url('admin.php?page=wp-updates-plugin-add&id=' . rawurlencode($box['id']))); ?>"><?php esc_html_e('Edit', 'wp-updates-plugin'); ?></a><a class="button button-link-delete" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=cdbm_delete_box&id=' . rawurlencode($box['id'])), 'cdbm_delete_box_' . $box['id'])); ?>" onclick="return confirm('<?php echo esc_js(__('Delete this card?', 'wp-updates-plugin')); ?>');"><?php esc_html_e('Delete', 'wp-updates-plugin'); ?></a></div></article><?php endforeach; ?></div><?php }
    private function categories_tab() { $categories = CDBM_Database::get_categories(); ?><div class="cdbm-tab-content"><h2><?php esc_html_e('Categories', 'wp-updates-plugin'); ?></h2><p><?php esc_html_e('Create categories once, then use their slugs when adding update cards or filtering the shortcode.', 'wp-updates-plugin'); ?></p><div class="cdbm-category-layout"><form class="cdbm-panel" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><h3><?php esc_html_e('Add new category', 'wp-updates-plugin'); ?></h3><?php wp_nonce_field('cdbm_save_category'); ?><input type="hidden" name="action" value="cdbm_save_category"><p><label for="cdbm-category-name"><?php esc_html_e('Category name', 'wp-updates-plugin'); ?></label><input class="regular-text" required id="cdbm-category-name" name="category" placeholder="<?php esc_attr_e('Example: Product updates', 'wp-updates-plugin'); ?>"></p><p class="description"><?php esc_html_e('The category is saved as a lowercase URL-friendly slug.', 'wp-updates-plugin'); ?></p><p><button class="button button-primary"><?php esc_html_e('Add category', 'wp-updates-plugin'); ?></button></p></form><div class="cdbm-panel"><h3><?php esc_html_e('Your categories', 'wp-updates-plugin'); ?></h3><?php if (!$categories) : ?><p><?php esc_html_e('No categories yet.', 'wp-updates-plugin'); ?></p><?php else : ?><ul class="cdbm-category-list"><?php foreach ($categories as $category) : ?><li><code><?php echo esc_html($category); ?></code><a class="button-link-delete" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=cdbm_delete_category&category=' . rawurlencode($category)), 'cdbm_delete_category_' . $category)); ?>" onclick="return confirm('<?php echo esc_js(__('Remove this category from all cards?', 'wp-updates-plugin')); ?>');"><?php esc_html_e('Remove', 'wp-updates-plugin'); ?></a></li><?php endforeach; ?></ul><?php endif; ?></div></div></div><?php }
    private function settings_tab() { $settings = CDBM_Database::get_settings(); ?><div class="cdbm-tab-content"><h2><?php esc_html_e('Settings', 'wp-updates-plugin'); ?></h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="cdbm_save_settings"><?php wp_nonce_field('cdbm_save_settings'); ?><table class="form-table"><tr><th><label for="cdbm-default-button-text"><?php esc_html_e('Default button text', 'wp-updates-plugin'); ?></label></th><td><input class="regular-text" id="cdbm-default-button-text" name="default_button_text" value="<?php echo esc_attr($settings['default_button_text']); ?>"><p class="description"><?php esc_html_e('Used whenever a card has a link but no custom button text.', 'wp-updates-plugin'); ?></p></td></tr></table><p class="submit"><button class="button button-primary"><?php esc_html_e('Save settings', 'wp-updates-plugin'); ?></button></p></form></div><?php }
    private function how_to_use_tab() { ?><div class="cdbm-tab-content cdbm-help"><h2><?php esc_html_e('How to use WP Updates', 'wp-updates-plugin'); ?></h2><ol><li><?php esc_html_e('Open the All cards tab and select Add card.', 'wp-updates-plugin'); ?></li><li><?php esc_html_e('Add a title, description, optional image and link, then assign one or more categories.', 'wp-updates-plugin'); ?></li><li><?php esc_html_e('Place the shortcode below in any page, post, or widget area.', 'wp-updates-plugin'); ?></li></ol><h3><?php esc_html_e('Shortcode examples', 'wp-updates-plugin'); ?></h3><p><code>[div_box]</code> <?php esc_html_e('Shows all cards in three columns.', 'wp-updates-plugin'); ?></p><p><code>[div_box columns="2" limit="6"]</code> <?php esc_html_e('Shows up to six cards in two columns.', 'wp-updates-plugin'); ?></p><p><code>[div_box categories="product-updates"]</code> <?php esc_html_e('Shows cards in one category. Use the slug listed in the Categories tab.', 'wp-updates-plugin'); ?></p></div><?php }
    public function edit_page() {
        if (!current_user_can('manage_options')) { wp_die(esc_html__('You do not have permission to manage cards.', 'wp-updates-plugin')); }
        $id = isset($_GET['id']) ? sanitize_text_field(wp_unslash($_GET['id'])) : ''; $box = $id ? CDBM_Database::get_div_box($id) : null; if ($id && !$box) { wp_die(esc_html__('Card not found.', 'wp-updates-plugin')); }
        $box = $box ?: array('id'=>'', 'title'=>'', 'description'=>'', 'image_id'=>0, 'image_url'=>'', 'button_url'=>'', 'button_text'=>'', 'categories'=>array()); ?>
        <div class="wrap"><h1><?php echo esc_html($id ? __('Edit update card', 'wp-updates-plugin') : __('Add update card', 'wp-updates-plugin')); ?></h1><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" id="cdbm-form"><?php wp_nonce_field('cdbm_save_box'); ?><input type="hidden" name="action" value="cdbm_save_box"><input type="hidden" name="id" value="<?php echo esc_attr($box['id']); ?>"><table class="form-table"><tbody>
        <tr><th><label for="cdbm-title"><?php esc_html_e('Title', 'wp-updates-plugin'); ?></label></th><td><input class="regular-text" required id="cdbm-title" name="title" value="<?php echo esc_attr($box['title']); ?>"></td></tr>
        <tr><th><label for="cdbm-description"><?php esc_html_e('Description', 'wp-updates-plugin'); ?></label></th><td><textarea class="large-text" required rows="5" id="cdbm-description" name="description"><?php echo esc_textarea($box['description']); ?></textarea></td></tr>
        <tr><th><label for="cdbm-categories"><?php esc_html_e('Categories', 'wp-updates-plugin'); ?></label></th><td><input class="regular-text" list="cdbm-category-suggestions" id="cdbm-categories" name="categories" value="<?php echo esc_attr(implode(', ', $box['categories'])); ?>"><datalist id="cdbm-category-suggestions"><?php foreach (CDBM_Database::get_categories() as $category) : ?><option value="<?php echo esc_attr($category); ?>"><?php endforeach; ?></datalist><p class="description"><?php esc_html_e('Enter one or more comma-separated category slugs. Manage saved categories from the Categories tab.', 'wp-updates-plugin'); ?></p></td></tr>
        <tr><th><?php esc_html_e('Image', 'wp-updates-plugin'); ?></th><td><div class="cdbm-image-upload"><div class="cdbm-image-preview" id="cdbm-image-preview"><?php if ($box['image_url']) : ?><img src="<?php echo esc_url($box['image_url']); ?>" alt=""><?php endif; ?></div><input type="hidden" id="cdbm-image-id" name="image_id" value="<?php echo esc_attr($box['image_id']); ?>"><input type="hidden" id="cdbm-image-url" name="image_url" value="<?php echo esc_url($box['image_url']); ?>"><button type="button" class="button" id="cdbm-select-image"><?php esc_html_e('Select image', 'wp-updates-plugin'); ?></button><button type="button" class="button" id="cdbm-remove-image"><?php esc_html_e('Remove image', 'wp-updates-plugin'); ?></button></div></td></tr>
        <tr><th><label for="cdbm-button-url"><?php esc_html_e('Optional button link', 'wp-updates-plugin'); ?></label></th><td><input class="regular-text" type="url" id="cdbm-button-url" name="button_url" value="<?php echo esc_url($box['button_url']); ?>"><p class="description"><?php esc_html_e('A button is displayed only when this link is provided.', 'wp-updates-plugin'); ?></p></td></tr>
        <tr><th><label for="cdbm-button-text"><?php esc_html_e('Button text', 'wp-updates-plugin'); ?></label></th><td><input class="regular-text" id="cdbm-button-text" name="button_text" value="<?php echo esc_attr($box['button_text']); ?>"><p class="description"><?php esc_html_e('Defaults to “Read more”.', 'wp-updates-plugin'); ?></p></td></tr>
        </tbody></table><p class="submit"><button class="button button-primary"><?php esc_html_e('Save card', 'wp-updates-plugin'); ?></button> <a class="button" href="<?php echo esc_url($this->url()); ?>"><?php esc_html_e('Cancel', 'wp-updates-plugin'); ?></a></p></form></div><?php
    }
    public function save() { if (!current_user_can('manage_options')) { wp_die(esc_html__('Not allowed.', 'wp-updates-plugin')); } check_admin_referer('cdbm_save_box'); $id = CDBM_Database::save_div_box(wp_unslash($_POST)); if (!$id) { wp_die(esc_html__('Title and description are required.', 'wp-updates-plugin')); } wp_safe_redirect($this->url(array('updated'=>1))); exit; }
    public function delete() { if (!current_user_can('manage_options')) { wp_die(esc_html__('Not allowed.', 'wp-updates-plugin')); } $id = isset($_GET['id']) ? sanitize_text_field(wp_unslash($_GET['id'])) : ''; check_admin_referer('cdbm_delete_box_' . $id); CDBM_Database::delete_div_box($id); wp_safe_redirect($this->url(array('deleted'=>1))); exit; }
    public function save_category() { if (!current_user_can('manage_options')) { wp_die(esc_html__('Not allowed.', 'wp-updates-plugin')); } check_admin_referer('cdbm_save_category'); CDBM_Database::add_category(wp_unslash($_POST['category'] ?? '')); wp_safe_redirect($this->url(array('tab' => 'categories', 'category-added' => 1))); exit; }
    public function delete_category() { if (!current_user_can('manage_options')) { wp_die(esc_html__('Not allowed.', 'wp-updates-plugin')); } $category = sanitize_title(wp_unslash($_GET['category'] ?? '')); check_admin_referer('cdbm_delete_category_' . $category); CDBM_Database::delete_category($category); wp_safe_redirect($this->url(array('tab' => 'categories', 'category-deleted' => 1))); exit; }
    public function save_settings() { if (!current_user_can('manage_options')) { wp_die(esc_html__('Not allowed.', 'wp-updates-plugin')); } check_admin_referer('cdbm_save_settings'); CDBM_Database::save_settings(wp_unslash($_POST)); wp_safe_redirect($this->url(array('tab' => 'settings', 'settings-saved' => 1))); exit; }
}
