<?php
if (!defined('ABSPATH')) { exit; }
class CDBM_Admin {
    public function __construct() { add_action('admin_menu', array($this, 'menu')); add_action('admin_post_cdbm_save_box', array($this, 'save')); add_action('admin_post_cdbm_delete_box', array($this, 'delete')); }
    public function menu() {
        add_menu_page(__('WP Updates Plugin', 'wp-updates-plugin'), __('WP Updates', 'wp-updates-plugin'), 'manage_options', 'wp-updates-plugin', array($this, 'list_page'), 'dashicons-megaphone', 30);
        add_submenu_page('wp-updates-plugin', __('All cards', 'wp-updates-plugin'), __('All cards', 'wp-updates-plugin'), 'manage_options', 'wp-updates-plugin', array($this, 'list_page'));
        add_submenu_page('wp-updates-plugin', __('Add card', 'wp-updates-plugin'), __('Add card', 'wp-updates-plugin'), 'manage_options', 'wp-updates-plugin-add', array($this, 'edit_page'));
    }
    private function url($args = array()) { return add_query_arg($args, admin_url('admin.php?page=wp-updates-plugin')); }
    public function list_page() {
        $boxes = CDBM_Database::get_div_boxes(); ?>
        <div class="wrap"><h1 class="wp-heading-inline"><?php esc_html_e('WP Updates', 'wp-updates-plugin'); ?></h1><a class="page-title-action" href="<?php echo esc_url(admin_url('admin.php?page=wp-updates-plugin-add')); ?>"><?php esc_html_e('Add card', 'wp-updates-plugin'); ?></a><hr class="wp-header-end">
        <?php if (isset($_GET['updated'])) : ?><div class="notice notice-success is-dismissible"><p><?php esc_html_e('Card saved.', 'wp-updates-plugin'); ?></p></div><?php endif; ?>
        <?php if (empty($boxes)) : ?><p><?php esc_html_e('No update cards yet.', 'wp-updates-plugin'); ?></p><?php else : ?><div class="cdbm-boxes-list"><?php foreach ($boxes as $box) : ?>
          <article class="cdbm-box-item"><div class="cdbm-box-preview"><div class="cdbm-preview-image"><?php if ($box['image_url']) : ?><img src="<?php echo esc_url($box['image_url']); ?>" alt=""><?php endif; ?></div><div class="cdbm-preview-content"><h3><?php echo esc_html($box['title']); ?></h3><p><?php echo esc_html(wp_trim_words($box['description'], 20)); ?></p><p><strong><?php esc_html_e('Categories:', 'wp-updates-plugin'); ?></strong> <?php echo esc_html(implode(', ', $box['categories'])); ?></p></div></div><div class="cdbm-box-actions"><a class="button button-primary" href="<?php echo esc_url(admin_url('admin.php?page=wp-updates-plugin-add&id=' . rawurlencode($box['id']))); ?>"><?php esc_html_e('Edit', 'wp-updates-plugin'); ?></a><a class="button button-link-delete" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=cdbm_delete_box&id=' . rawurlencode($box['id'])), 'cdbm_delete_box_' . $box['id'])); ?>" onclick="return confirm('<?php echo esc_js(__('Delete this card?', 'wp-updates-plugin')); ?>');"><?php esc_html_e('Delete', 'wp-updates-plugin'); ?></a></div></article>
        <?php endforeach; ?></div><?php endif; ?></div><?php
    }
    public function edit_page() {
        if (!current_user_can('manage_options')) { wp_die(esc_html__('You do not have permission to manage cards.', 'wp-updates-plugin')); }
        $id = isset($_GET['id']) ? sanitize_text_field(wp_unslash($_GET['id'])) : ''; $box = $id ? CDBM_Database::get_div_box($id) : null; if ($id && !$box) { wp_die(esc_html__('Card not found.', 'wp-updates-plugin')); }
        $box = $box ?: array('id'=>'', 'title'=>'', 'description'=>'', 'image_id'=>0, 'image_url'=>'', 'button_url'=>'', 'button_text'=>'', 'categories'=>array()); ?>
        <div class="wrap"><h1><?php echo esc_html($id ? __('Edit update card', 'wp-updates-plugin') : __('Add update card', 'wp-updates-plugin')); ?></h1><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" id="cdbm-form"><?php wp_nonce_field('cdbm_save_box'); ?><input type="hidden" name="action" value="cdbm_save_box"><input type="hidden" name="id" value="<?php echo esc_attr($box['id']); ?>"><table class="form-table"><tbody>
        <tr><th><label for="cdbm-title"><?php esc_html_e('Title', 'wp-updates-plugin'); ?></label></th><td><input class="regular-text" required id="cdbm-title" name="title" value="<?php echo esc_attr($box['title']); ?>"></td></tr>
        <tr><th><label for="cdbm-description"><?php esc_html_e('Description', 'wp-updates-plugin'); ?></label></th><td><textarea class="large-text" required rows="5" id="cdbm-description" name="description"><?php echo esc_textarea($box['description']); ?></textarea></td></tr>
        <tr><th><label for="cdbm-categories"><?php esc_html_e('Categories', 'wp-updates-plugin'); ?></label></th><td><input class="regular-text" id="cdbm-categories" name="categories" value="<?php echo esc_attr(implode(', ', $box['categories'])); ?>"><p class="description"><?php esc_html_e('Comma-separated tags, for example: updates, news. Use them in shortcodes to control which cards appear.', 'wp-updates-plugin'); ?></p></td></tr>
        <tr><th><?php esc_html_e('Image', 'wp-updates-plugin'); ?></th><td><div class="cdbm-image-upload"><div class="cdbm-image-preview" id="cdbm-image-preview"><?php if ($box['image_url']) : ?><img src="<?php echo esc_url($box['image_url']); ?>" alt=""><?php endif; ?></div><input type="hidden" id="cdbm-image-id" name="image_id" value="<?php echo esc_attr($box['image_id']); ?>"><input type="hidden" id="cdbm-image-url" name="image_url" value="<?php echo esc_url($box['image_url']); ?>"><button type="button" class="button" id="cdbm-select-image"><?php esc_html_e('Select image', 'wp-updates-plugin'); ?></button><button type="button" class="button" id="cdbm-remove-image"><?php esc_html_e('Remove image', 'wp-updates-plugin'); ?></button></div></td></tr>
        <tr><th><label for="cdbm-button-url"><?php esc_html_e('Optional button link', 'wp-updates-plugin'); ?></label></th><td><input class="regular-text" type="url" id="cdbm-button-url" name="button_url" value="<?php echo esc_url($box['button_url']); ?>"><p class="description"><?php esc_html_e('A button is displayed only when this link is provided.', 'wp-updates-plugin'); ?></p></td></tr>
        <tr><th><label for="cdbm-button-text"><?php esc_html_e('Button text', 'wp-updates-plugin'); ?></label></th><td><input class="regular-text" id="cdbm-button-text" name="button_text" value="<?php echo esc_attr($box['button_text']); ?>"><p class="description"><?php esc_html_e('Defaults to “Read more”.', 'wp-updates-plugin'); ?></p></td></tr>
        </tbody></table><p class="submit"><button class="button button-primary"><?php esc_html_e('Save card', 'wp-updates-plugin'); ?></button> <a class="button" href="<?php echo esc_url($this->url()); ?>"><?php esc_html_e('Cancel', 'wp-updates-plugin'); ?></a></p></form></div><?php
    }
    public function save() { if (!current_user_can('manage_options')) { wp_die(esc_html__('Not allowed.', 'wp-updates-plugin')); } check_admin_referer('cdbm_save_box'); $id = CDBM_Database::save_div_box(wp_unslash($_POST)); if (!$id) { wp_die(esc_html__('Title and description are required.', 'wp-updates-plugin')); } wp_safe_redirect($this->url(array('updated'=>1))); exit; }
    public function delete() { if (!current_user_can('manage_options')) { wp_die(esc_html__('Not allowed.', 'wp-updates-plugin')); } $id = isset($_GET['id']) ? sanitize_text_field(wp_unslash($_GET['id'])) : ''; check_admin_referer('cdbm_delete_box_' . $id); CDBM_Database::delete_div_box($id); wp_safe_redirect($this->url(array('deleted'=>1))); exit; }
}